name: boma
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  june: ^1.0.0+1
  go_router: ^14.6.2
  intl_phone_field: ^3.2.0
  google_maps_flutter: ^2.10.0
  location: ^7.0.1
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  dio: ^5.7.0
  # image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  